[project]
name = "evoland-plus-darwin"
r_version = "4.5"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
    { alias = "CRAN", url = "https://stat.ethz.ch/CRAN/" },
]

# A list of packages to install and any additional configuration
# Examples:
dependencies = [
    "curl",
    "data.table",
    "DBI",
    "duckdb",
    "glue",
    "lubridate",
    "pxR",
    "tidyverse",
    # dev dependencies
    "devtools",
    "httpgd",
    "languageserver",
    "mirai",
    "quarto",
    "rlang",
    "rmarkdown",
    "writexl",
    "svglite",
    { name = "evoland", git = "https://github.com/ethzplus/evoland-plus/", commit = "b40175fd048c1615ff66e4fa556f6a0cd863b3fe", install_suggestions = true },
    # { name = "evoland", path = "../evoland-plus-darwin" , install_suggestions = true },
]
