[project]
name = "evoland-plus-darwin"
r_version = "4.6"

repositories = [
    { alias = "CRAN", url = "https://p3m.dev/cran/latest" },
]

# A list of packages to install and any additional configuration
# Examples:
dependencies = [
    "curl",
    "data.table",
    "DBI",
    "duckdb",
    "glue",
    "lubridate",
    "pxR",
    "tidyverse",
    # too many issues with GDAL linking otherwise
    { name = "terra", force_source = true },
    { name = "sf", force_source = true },
    # dev dependencies
    "devtools",
    "httpgd",
    "languageserver",
    "mirai",
    "quarto",
    "rlang",
    "rmarkdown",
    "writexl",
    "svglite",
    { name = "evoland", git = "https://github.com/ethzplus/evoland-plus/", commit = "31658c7110affd4f94d2696191dd048920dc99df", install_suggestions = true },
    "mapview",
    "stars",
    "methods",
    "terra",
    "yaml",
    "mlr3learners",
    "e1071",
    "future.mirai",
    "ggspatial",
    "viridis",
]
